id: "SRV_NAME"
main-worldname: "Isolonice"
main-world-spawn-coordinate: "0;60;0"
inactivity-before-world-unload: 15
sql:
  server: "IP_ADDRESS"
  port: 3306
  database: "DATABASE_NAME"
  username: "DATABASE_USERNAME"
  password: "PASSWORD"