name: Isoworlds
version: @version@
main: bukkit.Main
authors: [Sythiel]
description: Large scale personal world manager
load: STARTUP
website: https://isolonice.fr

commands:
    iw:
        description: Base command
        usage: /<iw> [creation][liste][maison][confiance][on][off][teleport]
        aliases: [Isoworlds, isoworld]

permissions:
    Isoworlds.default:
        description: Allow Isoworlds usage
        defaut: true