name: Iworlds
version: @version@
main: bukkit.IworldsBukkit
authors: [Sythiel]
description: Manager de mondes personnels
website: https://isolonice.fr

commands:
    iw:
        description: Commande de base des iworlds
        usage: /<iw> [creation][liste][maison][confiance][on][off][teleport]
        aliases: [iworlds, iworld]

permission:
    iworlds.default:
      description: Autoriser une utilisation des iworlds
      defaut: true