name: Isoworlds
version: @version@
main: bukkit.IsoworldsBukkit
authors: [Sythiel]
description: Manager de mondes personnels
website: https://isolonice.fr

commands:
    iw:
        description: Commande de base des isoworlds
        usage: /<iw> [creation][liste][maison][confiance][on][off][teleport]
        aliases: [isoworlds, isoworld]

permission:
    isoworlds.default:
      description: Autoriser une utilisation des iworlds
      defaut: true