name: Isoworlds
version: @version@
main: bukkit.IsoworldsBukkit
authors: [Sythiel]
description: Manager de mondes personnels
website: https://isolonice.fr

commands:
    iw:
        description: Commande de base des isoworlds
        usage: /<iw> [creation][liste][maison][confiance][on][off][teleport]
        aliases: [isoworlds, isoworld]

permission:
    isoworlds.default:
      description: Autoriser une utilisation des iworlds
      defaut: true
    isoworlds.unlimited.charges:
      description: Autoriser l'utilisation des charges sans en posséder
      default: false
    isoworlds.size.500:
      description: Taille du monde: 500
      default: false
    isoworlds.size.750:
      description: Taille du monde: 750
      default: false
    isoworlds.size.1000:
      description: Taille du monde 1000
      default: false
    isoworlds.bypass.spawn:
      description: Permet d'intéragir avec le spawn
      default: false