name: Isoworlds
version: @version@
main: bukkit.IsoworldsBukkit
authors: [Sythiel]
description: Large scale personal world manager
load: STARTUP
website: https://isolonice.fr

commands:
    iw:
        description: Base command
        usage: /<iw> [creation][liste][maison][confiance][on][off][teleport]
        aliases: [isoworlds, isoworld]

permissions:
    isoworlds.default:
        description: Allow isoworlds usage
        defaut: true